DATA SEGMENT
A DW 1111H  ; A = 1111
B DW 2222H  ; B = 2222
C DW ?      ; C = NULL
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:

MOV AX, DATA    ; LOADING DATA SEGMENT TO AX (ACCUMULATOR)
MOV DS, AX      ; LOADING DATA SEGMENT FROM AX TO DS

MOV AX, A       ; LOADING A TO AX
MOV BX, B       ; LOADING B TO BX REGISTER
ADD AX, BX      ; ADDING BX TO AX (AX = AX + BX)

MOV C, AX       ; LOADING AX TO C (Result)

INT 3           ; INTERRUPT TO END PROGRAM
CODE ENDS
END START
