DATA SEGMENT
A DW 0005H  ; A = 5
B DW 0004H  ; B = 4
C DW ?      ; C = NULL
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA

START:
MOV AX, DATA    ; LOADING DATA SEGMENT INTO AX
MOV DS, AX      ; LOADING AX IN DS

MOV AX, A       ; LOADING A IN AX (ACCUMULATOR)
MOV BX, B       ; LOADING B IN BX REGISTER

MUL BX          ; MULTIPLYING BX WITH AX (ACCUMULATOR)

MOV WORD PTR C, AX      ; LOADING AX IN C
MOV WORD PTR C+2, DX    ; LOADING AX IN C (to 2nd WORD)

INT 3       ; INTERRUPT TO END PROGRAM
CODE ENDS
END START
