DATA SEGMENT
A DW 5555H  ; A = 5555
B DW 2222H  ; B = 2222
C DW ?      ; C = NULL
DATA ENDS

CODE SEGMENT
ASSUME CS:CODE, DS:DATA
START:

MOV AX, DATA    ; LOADING DATA SEGMENT TO AX (ACCUMULATOR)
MOV DS, AX      ; LOADING DATA SEGMENT FROM AX TO DS

MOV AX, A       ; LOADING A IN AX (ACCUMULATOR)
MOV BX, B       ; LOADING B IN BX REGISTER

SUB AX, BX      ; SUBTRACTING BX FROM AX (AX = AX - BX)

MOV C, AX       ; LOADING AX INTO C

INT 3           ; INTERRUPT TO END PROGRAM
CODE ENDS
END START
